### PR TITLE
perf: Improved Performance of Incrementing Prayers

### PR DESCRIPTION
**Pull request by briankalwat**
### What does this PR do, or why is it needed?

This PR updates the createInteraction query - particularly the subquery that checks to see when the last notification was sent to the user - to use the lava endpoint, which in this context is more performant (~13x faster).

### How do I test this PR?

Running the api locally, run the `incrementPrayerCount` mutation using current code vs new code (I used postman to actually see duration of request/response).

```
mutation {
  incrementPrayerCount(nodeId: "Prayer:60d5cb69c96378192c2e12d5cda5a03d") {
    text
  }
}
```

## TODO

- [X] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [X] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [X] No new warnings
- [ ] Upload Screenshots/GIF(s) if applicable
- [X] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

---

> The purpose of a PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
We should discuss implications of SQL injection here

**Comment by redreceipt** [comment]
also @briankalwat for future, the PR title needs to be short and easy to understand in release notes

**Comment by briankalwat** [comment]
@redreceipt Got it. Using "Bugfixes and Performance Enhancements" from here on out for every PR. 🚀

**Comment by briankalwat** [comment]
@redreceipt @richarddubay do we want to get together at some point and discuss how we want to actually implement this and things like it in the future?

**Comment by redreceipt** [comment]
Don’t think that’s necessary. Out of the convo with TIim, I’d say we’re safe to pass data not touched by users (like the user ID) here. I’d say code up your previous solution and submit the PR. We can talk about how to further abstract and make it better in other tasks.

—
Michael

**Comment by redreceipt** [comment]
So if you’re asking my opinion, I like having the SQL in our code vs lava mappings. One less place to look and debug when things go wrong.

—
Michael

**Pull request merged**
