### PR TITLE
Adds Events to Home Feed

### PR DESCRIPTION
**Pull request by redreceipt**
## DESCRIPTION

Screen Shot 2020-07-06 at 4 10 44 PM

Screen Shot 2020-07-06 at 4 05 34 PM

### What does this PR do, or why is it needed?

Adds campus events to the home feed

### How do I test this PR?

Pull up the app and see them magically appear

## TODO

- [x] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings
- [x] Upload Screenshots/GIF(s) if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

---

> The purpose of a PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by richarddubay** [comment]
Could just be me testing incorrectly? But events don't show in the app for me and I get this in the console.

Screenshot 2020-07-16 09 06 19

**Comment by redreceipt** [comment]
Those are bad request errors, have you tried them in swagger or Postman?

—
Michael

**Comment by richarddubay** [comment]
No, I hadn't before you said something. Looking closer, it looks like it's trying to pull an `EventItemId` that's equal to `object Object`. That's probably where the problem lies.

**Comment by richarddubay** [comment]
@redreceipt Any thoughts on this one?

**Comment by redreceipt** [comment]
oh no, I started to look in and forgot. Let me dive in...

**Comment by redreceipt** [comment]
fixed it

**Comment by richarddubay** [comment]
@redreceipt There are a couple things I'm noticing in the UI, mostly related to recurring events, that don't seem to be right. Should I mention those here or create a different task to handle those? At the end of the day I think the problems _probably_ come down to data, so that's why I'm asking here.

**Comment by redreceipt** [comment]
might as well mention them here. if we both decide they are data problems, we're safe in that events are still experimental and there's no actual valid data in there yet.

**Comment by richarddubay** [comment]
Okay so looking at recurring events specifically. On the event detail page, when there is no end time, it shows like 12AM - 12AM. It also shows the original date that the item was created and not the next occurance of the item.
Screenshot 2020-07-23 13 42 55
Screenshot 2020-07-23 13 47 06
Screenshot 2020-07-23 13 47 53

**Comment by richarddubay** [comment]
I think I would expect it to show either just the start time, or no time at all if it was like an all day event. And I definitely would expect it to show the next occurrence date.

**Comment by redreceipt** [comment]
ok so either we hold this PR up until we fix how events are parsed or we merge and fix that in another PR. I vote the former but it's up to you.

**Comment by redreceipt** [comment]
I meant I vote the latter :)

**Comment by richarddubay** [comment]
Since this is marked `experimental` I have no problems merging this now. We'll have to come back to this later anyway. Let's just not forget. 👍

**Pull request merged**
