### PR TITLE
chore: Removes custom code from auth

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

With the new auth flow, we can take out our custom authenticate function! And I figured we could go ahead and remove everything while we're at it.

### How do I test this PR?

Login.

## TODO

- [x] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings
- [x] Upload Screenshots/GIF(s) if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

---

> The purpose of a PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by richarddubay** [comment]
What is it about the new auth flow that allows us to remove our custom stuff? I'm mostly concerned with the bit we had about removing the end of the email address so that staff could sign in with AD. I'm not familiar enough with what the new auth flow does.

**Comment by richarddubay** [comment]
Also, do we have this flow yet? I shouldn't merge this until we have that I would assume.

**Comment by redreceipt** [comment]
After our convo, we decided the very small chance that someone was confused by a different password is not worth adding all the technical debt

—
Michael

**Comment by richarddubay** [comment]
This still needs to wait until we have that new flow, right? How will we know when we have it?

**Comment by redreceipt** [comment]
What do you mean? This one should be good to go now.


--
Michael Neeley
Junior Web Developer
NewSpring Church
www.newspring.cc
Cell: (803) 622-6599

**Comment by richarddubay** [comment]
You said "with the new auth flow..." and I am just unsure if we already have the new auth flow. I know we have a new phone number entry screen ... but that's not the entire flow. Do we need to wait for the entire new flow before we do this? Do we already have the entire new flow? If not, and we need to wait for it, do you know when it's coming?

I just don't want to merge something we aren't prepared for because we're waiting on changes from core.

**Comment by redreceipt** [comment]
I mean I tested our app with this change and it behaves right. Don't think
we're waiting on anything here. But confirm you can sign in with your work
email to make sure.


--
Michael Neeley
Junior Web Developer
NewSpring Church
www.newspring.cc
Cell: (803) 622-6599

**Pull request merged**
