### PR TITLE
fix: Prayer notification interaction correctly created for new prayers

### PR DESCRIPTION
**Pull request by richarddubay**
### What does this PR do, or why is it needed?
This PR adds a check to the `summary` calculation so that if the `result` of the check to see the last time that a prayer notification comes back empty (meaning it has never had a prayer notification interaction) then set the summary correctly so that a prayer notification is triggered.

That `RenderTemplate` API endpoint returns "" if it cannot find an interaction with a summary of "PrayerNotificationSent" for a particular prayer. When this happens, the call to `moment` to get 2 hours back fails, so the summary is never set to "PrayerNotificationSent" and the prayer never gets a notification. 

This change makes it so that if the `result === ''` then we automatically set the summary to "PrayerNotificationSent" so that the prayer gets a notification.

** NOTE **: Also this looks like it might be a fix of the prayer interaction time discrepancy as well. When I test from the app on my phone I get the 4 hour difference in time but when I test from this branch the times are correct.
 
### How do I test this PR?
Pray for a brand new prayer and make sure that a prayer interaction with a summary of "PrayerNotificationSent" is correctly created.

## TODO

- [x] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings
- [x] Upload Screenshots/GIF(s) if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

---

> The purpose of a PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
Are we sure that `result` doesn't come back `""` for any other reason? This makes me nervous because we're assuming if an empty string comes back, it worked.

**Comment by redreceipt** [comment]
And we'll need test coverage

**Comment by richarddubay** [comment]
@redreceipt So I've been picking at tests for this for a little bit. I'm not sure how to test this ... but only because the function doesn't actually return anything to snapshot. It just posts an interaction. I wrote some tests but the snapshots just show `undefined`. Is there someplace else that we do something similar that we actually test? Or do you know how to test this?

This is what I've got:
```
it('creates a prayer interaction', async () => {
    Prayer.context.dataSources.Auth = {
      getCurrentPerson: () => ({ id: 'Person123' }),
    };
    Prayer.post = () => ({
      result: '12-31-2019 01:01:01AM',
    });
    Prayer.fetch = () => jest.fn();
    Prayer.getInteractionComponent = () => ({ id: 1 });
    expect(await Prayer.createInteraction(123456)).toMatchSnapshot();
  });
```

**Comment by richarddubay** [comment]
@redreceipt Got that ✅  on tests now.

**Pull request merged**
