### PR TITLE
chore: Removes Loadtesting from API Library

### PR DESCRIPTION
**Pull request by redreceipt**
### What does this PR do, or why is it needed?

This doesn't really need to be in here. Just takes up space and it's never really used. We should use Blazemeter for consistent QAs.

### How do I test this PR?

Boot up the server.

## TODO

- [x] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings
- [ ] Upload Screenshots/GIF(s) if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

---

> The purpose of a PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by richarddubay** [comment]
@redreceipt This looks good. If you could just tidy up that `yarn.lock` file I'll get this one merged!

**Comment by redreceipt** [comment]
What’s wrong with the yarn lock file?

—
Michael

**Comment by richarddubay** [comment]
The PR just says there are conflicts. 

Screen Shot 2020-06-01 at 10 25 39 AM

**Comment by redreceipt** [comment]
Ah. Done.

—
Michael

**Pull request merged**
