### PR TITLE
chore: Update API to use InteractionsChannelId

### PR DESCRIPTION
**Pull request by richarddubay**
### What does this PR do, or why is it needed?
This PR updates the interactions component lookup when writing interactions to use the renamed `InteractionChannelId` (instead of the old `ChannelId`).

*****NOTE*****
This can be merged but should not be deployed to the production API until production Rock is updated. Once this PR gets merged I will let Paul know that he can do the production release once production Rock is updated.

### How do I test this PR?
Just make sure that prayer interactions still work. When you pray for a prayer you should get an interaction in the Interaction table just like before. Nothing should look different.

P.S. You should test this on `alpha-rock` since the renamed DB column doesn't exist in production.

## TODO

- [x] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings
- [x] Upload Screenshots/GIF(s) if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

---

> The purpose of a PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by redreceipt** [comment]
Don't we use interactions for liking content too?

**Comment by richarddubay** [comment]
@redreceipt Actually, likes use `Followings`.

**Comment by richarddubay** [comment]
Yeah I get that too. I'll fix that up.

**Comment by richarddubay** [comment]
Okay @redreceipt. I updated this so that:
* Writes the interaction using local time and not GMT. The `InteractionDateTime` was being set 4 hours ahead ... which seemed broken.
* Took care of the warning by formatting `result`. It didn't like it when trying to do `moment(result)` because it didn't like the format it was in.
* Added some tests. Straight copied them (and the `test-utils.js` file) from core. Not exactly sure if this is the best way to handle it or not. I'm open to suggestions.

**Comment by redreceipt** [comment]
i was gonna hold this up by seeing if we needed that tests utils function but not worth it. looks good.

**Pull request merged**
