### PR TITLE
fix: (DEV-4300) Fixes Devotionals with Multiple Scriptures

### PR DESCRIPTION
**Pull request by redreceipt**

### CODE REVIEW

**Comment by richarddubay** [comment]
@redreceipt Okay, so I tested this and it works. But I'm not really fond of the sorting. I mean, I don't hate it, but is it necessary? Maybe there's another way to do it? I feel like having to do the "adding a zero then taking a zero off" thing is kind of hacky.

**Comment by richarddubay** [comment]
@redreceipt Do we want to pursue a different sorting thing here?

**Comment by redreceipt** [comment]
I don't have a better idea

**Comment by redreceipt** [comment]
@richarddubay can we move on this? I get if this was a feature and we were looking for the best way to do things, but this is a bug fix and should be treated as such. We can circle around later and come up with a better algorithm later.

**Comment by richarddubay** [comment]
I can test this again and make sure it still works and merge it but here's the deal ... we won't come back to it. We haven't looked at it in the 4 months since I made my first comment. So let's not kid ourselves and think we're going to make this better later. We won't or we would have already.

**Pull request merged**
